name: GPT→Notion Sync

on:
  schedule:
    - cron: '0 19 * * *'      # 毎日04:00 JST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai notion-client beautifulsoup4 python-dotenv

      - name: Run sync script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NOTION_TOKEN:   ${{ secrets.NOTION_TOKEN }}
          NOTION_DB:      ${{ secrets.NOTION_DB }}
        run: python sync.py
